services:
  minecraft:
    image: itzg/minecraft-server
    # run as user dockermc (1001) and its group (1001)
    user: "1001:1001"
    # limit the max memory and number of CPUs the container can use
    #mem_limit: 1900M
    #cpus: "0.5"
    deploy:
      resources:
        limits:
          memory: 1900M
          cpus: 1
        reservations:
          memory: 1600M
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      TYPE: VANILLA
      ONLINE_MODE: TRUE
      INIT_MEMORY: 1500M
      MAX_MEMORY: 1800M
      MODE: creative
      DIFFICULTY: easy
      PVP: FALSE
      MAX_PLAYERS: 5
      #TYPE: FORGE
      #FORGE_INSTALLER_URL: https://github.com/CleanroomMC/Cleanroom/releases/download/0.2.4-alpha/cleanroom-0.2.4-alpha-installer.jar
      # always restore the whitelist with users set via env variable
      #EXISTING_WHITELIST_FILE: "SYNCHRONIZE"
      #WHITELIST: |
      #  YouPlayerName
      #  FriendsPlayerName        
      # always restore the ops with users set via env variables
      #EXISTING_OPS_FILE: "SYNCHRONIZE"
      #OPS: |
      #  YouPlayerName        
      SNOOPER_ENABLED: FALSE
      #server.properties https://minecraft.wiki/w/Server.properties
      #MOTD (Message of the day) https://minecraft.wiki/w/Formatting_codes
      MOTD: |
        §c§lMinecraft§r§r Ивана
        тип %TYPE%, версия %VERSION%

    volumes:
      - ./data:/data
      - ./server-icon.png:/server-icon.png
