name: Minecraft (vanilla)
on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: Minecraft version, default 1.21.11
        required: true
        default: '1.21.11'
        type: string


permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: firstbyte
      url: https://github.com/detilol/minecraft-on-docker/settings/environments
    if: github.ref == 'refs/heads/master'
    container:
      image: skipero/neat-ci:latest
    env:
      SSH_URL: ${{ secrets.SSH_URL }}/${{ github.head_ref || github.ref_name }}/
      MC_VERSION: ${{ inputs.minecraft_version }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: Stop docker compose on target server
        run: npx -y --package uzdu -- uzdu exec ssh $SSH_URL 'docker compose down'
        continue-on-error: true
      - name: Upload to target server
        if: ${{ always() }}
        env:
          command: docker compose up -d -e VERSION=${{ env.MC_VERSION }} 
        run: npx uzdu upload ssh ./recipes/1 $SSH_URL
      - name: Start docker compose on target server 
        run: npx -y --package uzdu -- uzdu exec ssh $SSH_URL "docker compose up -d -e VERSION=$MC_VERSION"

